# -*- coding: utf-8 -*-
"""cw5-11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hT366JPRykhoLjFRythocjL9hnjfNqiI
"""
# ปล อันนี้แค่ลอกโค้ดจากสไลด์มา ซึ่งมันเป็นการแปลง UTM ด้วย pyproj แนะนำให้ทำใน jupyter 
# หรือไม่ก็ควรมีconda ง่ายที่สุดก็คือทำใน google colab 
# วิธีติดตั้ง pyproj ใน colab
# ! pip install pyproj

from pyproj import Transformer, Proj
# proj4 definition
LL_W84 = '+proj=longlat +datum=WGS84 +no_defs '
UTM_W84z47 = '+proj=tmerc +ellps=WGS84 +lon_0=99 +x_0=500000 +k=0.9996 +towgs84=0,0,0'
UTM_I75z47 = '+proj=tmerc +ellps=evrst30 +lon_0=99 +x_0=500000 +k=0.9996 +towgs84=206,837,295'
#pyproj Proj object
ll_w84 = Proj(LL_W84)
utm_w84z47 = Proj(UTM_W84z47)
utm_i75z47 = Proj(UTM_I75z47)
# WGS84 LngLat to WGS84 UTM-z47
tr = Transformer.from_proj(ll_w84 , utm_w84z47)
points = [(100,14),]
for pt in tr.itransform(points):
  print('{:.3f} {:.3f} '.format(*pt))
# WGS84 LngLat to WGS84 UTM-z47
tr = Transformer.from_proj(ll_w84 , utm_i75z47)
points = [(100,14),]
for pt in tr.itransform(points):
  print('{:.3f} {:.3f} '.format(*pt))
